### ISSUE TITLE
HubiC

### ISSUE THREAD

**Issue by macropin** [gaul/object-store-comparison#24]
I believe this qualifies as object storage and should be listed. They have implemented the OpenStack API.

https://api.hubic.com/

**Comment by andrewgaul** [comment]
Sounds good -- could you submit a pull request?

**Comment by alexanderkjeldaas** [comment]
I don't think it should be listed. HubiC prohibits commercial use.  Max 10Mbps communications etc.  It's not a "real" object storage.

**Comment by macropin** [comment]
T&C's are in french https://hubic.com/fr/contracts/Contrat_hubiC_2014.pdf

**Comment by macropin** [comment]
I just tested their Hubic with rclone. Hopelessly unreliable. I have to agree not worth listing.
